"""auto

Revision ID: 0001
Revises:
Create Date: 2024-03-03 13:46:00.883212

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auth__user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False
        ),
        sa.Column('username', sa.String(length=256), nullable=False),
        sa.Column('password_hash', sa.String(length=256), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column(
            'role',
            sa.Enum('ADMIN', 'MANAGER', 'EMPLOYEE', 'ACCOUNTANT', name='role'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('public_id'),
        sa.UniqueConstraint('username'),
    )
    op.create_table(
        'oauth__client',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('client_id', sa.String(length=48), nullable=False),
        sa.Column('client_secret', sa.String(length=120), nullable=False),
        sa.Column('redirect_url', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_index(op.f('ix_oauth__client_client_id'), 'oauth__client', ['client_id'], unique=True)
    op.create_table(
        'oauth__code',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(length=120), nullable=False),
        sa.Column('auth_time', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['oauth__client.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['auth__user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth__code')
    op.drop_index(op.f('ix_oauth__client_client_id'), table_name='oauth__client')
    op.drop_table('oauth__client')
    op.drop_table('auth__user')
    # ### end Alembic commands ###
