"""auto

Revision ID: 0002
Revises: 0001
Create Date: 2024-03-09 13:03:25.436870

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accounting__account',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('balance', sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['auth__user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'accounting__billing_cycle',
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('start_dt', sa.DateTime(), nullable=False),
        sa.Column('end_dt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounting__account.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'accounting__transaction',
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('billing_cycle_id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('processing_dt', sa.DateTime(), nullable=False),
        sa.Column('credit', sa.Numeric(), nullable=False),
        sa.Column('debit', sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['accounting__account.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['billing_cycle_id'], ['accounting__billing_cycle.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['task_id'], ['tracker__task.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounting__transaction')
    op.drop_table('accounting__billing_cycle')
    op.drop_table('accounting__account')
    # ### end Alembic commands ###
