"""auto

Revision ID: 0003
Revises: 0002
Create Date: 2024-03-10 14:02:57.095981

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tracker__task',
        sa.Column('jira_id', sa.String(length=30), server_default='', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker__task', 'jira_id')
    # ### end Alembic commands ###
